name: Flutter Desktop CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            build: windows
          - os: macos-latest
            build: macos
          - os: ubuntu-latest
            build: linux

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.19.4'
          
      - name: Enable desktop support
        run: flutter config --enable-desktop
        
      - name: Install dependencies
        run: flutter pub get
        
      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
        
      - name: Build desktop app
        run: flutter build ${{ matrix.build }} --release
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build }}-release
          path: build/${{ matrix.build }}/release/bundle