name: Flutter Desktop CI/CD

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [dev,main]

jobs:

  set-environment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-environment.outputs.environment }}
    steps:
      - name: set environment
        id: set-environment
        run: |
          echo ${{ github.base_ref }}
          echo "environment=dev" >> $GITHUB_OUTPUT
          if [ ${{ github.base_ref }} == "main" ]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          fi
      - name: check environment
        run: echo ${{ steps.set-environment.outputs.environment }}

  build:
    environment: ${{ needs.set-environment.outputs.environment }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            build: windows
          - os: macos-latest
            build: macos
    runs-on: ${{ matrix.os }}
    needs: [set-environment]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.19.4'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
          
      - name: Clean pub cache (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Get-Process | Where-Object {$_.ProcessName -match 'dart|pub|flutter'} | Stop-Process -Force -ErrorAction SilentlyContinue
          flutter clean
          Start-Sleep -Seconds 2
          Get-ChildItem -Path "$env:LOCALAPPDATA\Pub\Cache","$env:APPDATA\.pub-cache","$env:USERPROFILE\.pub-cache" -Recurse -ErrorAction SilentlyContinue | 
            Remove-Item -Force -Recurse -ErrorAction SilentlyContinue
          
      - name: Clean pub cache (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          flutter clean
          flutter pub cache repair
          rm -rf ~/Library/Caches/pub
          rm -rf ~/.pub-cache
          
      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          flutter config --no-analytics
          flutter pub get
          
      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          flutter config --no-analytics
          flutter pub get
        
      - name: Run build_runner
        run: |
          dart pub global activate flutter_gen_runner
          flutter pub run build_runner build --delete-conflicting-outputs
        
      - name: Build desktop app
        run: |
          flutter config --enable-windows-desktop
          flutter config --enable-macos-desktop
          flutter build ${{ matrix.build }} --release
        
      - name: Upload Windows artifact
        if: matrix.os == 'windows-latest'
        id: upload-windows-artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: build/windows/x64/runner/Release/
          
      - name: Upload macOS artifact
        if: matrix.os == 'macos-latest'
        id: upload-macos-artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-release
          path: build/macos/Build/Products/Release/

      - name: Notify Slack on Success
        if: always()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "${{ job.status == 'success' && '✅' || '❌' }} Flutter Desktop ${{ matrix.build }} 빌드\n배포환경: ${{ needs.set-environment.outputs.environment }}\n성공 유무: ${{ job.status }}\nOS: ${{ matrix.os }}\n저장소: ${{ github.repository }}\n브랜치: ${{ github.ref }}\n\n아티팩트 다운로드: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING-WEBHOOK