name: Flutter Desktop CI/CD

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [dev,main]

jobs:

  set-environment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-environment.outputs.environment }}
    steps:
      - name: set environment
        id: set-environment
        run: |
          echo ${{ github.base_ref }}
          echo "environment=dev" >> $GITHUB_OUTPUT

          if [ ${{ github.base_ref }} == "main" ]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          fi
      - name: check environment
        run: echo ${{ steps.set-environment.outputs.environment }}

  build:
    environment: ${{ needs.set-environment.outputs.environment }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            build: windows
          - os: macos-latest
            build: macos
    runs-on: ${{ matrix.os }}
    needs: [set-environment]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.19.4'
          architecture: x64
          cache: true
          
      - name: Windows Setup
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          flutter config --enable-windows-desktop
          $env:PUB_CACHE = "${{ github.workspace }}/.pub-cache"
          mkdir -Force $env:PUB_CACHE
          
          # Kill any potential Flutter/Dart processes with more thorough cleanup
          Get-Process -Name "dart" -ErrorAction SilentlyContinue | ForEach-Object { 
            try { 
              Stop-Process -Id $_.Id -Force -ErrorAction Stop
              Start-Sleep -Seconds 1
            } catch { 
              Write-Host "Failed to stop process $($_.Id): $_"
            }
          }
          
          Get-Process -Name "flutter" -ErrorAction SilentlyContinue | ForEach-Object { 
            try { 
              Stop-Process -Id $_.Id -Force -ErrorAction Stop
              Start-Sleep -Seconds 1
            } catch { 
              Write-Host "Failed to stop process $($_.Id): $_"
            }
          }
          
          # Additional cleanup for any remaining processes
          Get-Process | Where-Object { $_.ProcessName -like "*dart*" -or $_.ProcessName -like "*flutter*" } | 
            ForEach-Object { 
              try { 
                Stop-Process -Id $_.Id -Force -ErrorAction Stop
                Start-Sleep -Seconds 1
              } catch { 
                Write-Host "Failed to stop process $($_.Id): $_"
              }
            }
          
          # Wait for processes to fully terminate
          Start-Sleep -Seconds 5
          
          # Clean up directories with improved retry mechanism
          $maxRetries = 3
          $retryCount = 0
          $retryDelay = 5
          
          while ($retryCount -lt $maxRetries) {
            try {
              Write-Host "Attempt $($retryCount + 1) of $maxRetries to clean directories"
              
              # Check if directories exist before trying to remove
              if (Test-Path ".dart_tool") {
                Remove-Item -Path ".dart_tool" -Recurse -Force -ErrorAction Stop
                Write-Host "Successfully removed .dart_tool"
              }
              
              if (Test-Path "build") {
                Remove-Item -Path "build" -Recurse -Force -ErrorAction Stop
                Write-Host "Successfully removed build directory"
              }
              
              if (Test-Path "pubspec.lock") {
                Remove-Item -Path "pubspec.lock" -Force -ErrorAction Stop
                Write-Host "Successfully removed pubspec.lock"
              }
              
              break
            } catch {
              $retryCount++
              Write-Host "Error during cleanup: $_"
              
              if ($retryCount -eq $maxRetries) {
                Write-Host "Failed to clean directories after $maxRetries attempts"
                exit 1
              }
              
              Write-Host "Waiting $retryDelay seconds before retry..."
              Start-Sleep -Seconds $retryDelay
              $retryDelay *= 2  # Exponential backoff
            }
          }
          
          Write-Host "Directory cleanup completed successfully"
          
      - name: macOS Setup
        if: matrix.os == 'macos-latest'
        run: |
          flutter config --enable-macos-desktop
          
      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          # Kill any potential Flutter/Dart processes before clean
          Get-Process -Name "dart" -ErrorAction SilentlyContinue | Stop-Process -Force
          Get-Process -Name "flutter" -ErrorAction SilentlyContinue | Stop-Process -Force
          
          # Run flutter clean with retry mechanism
          $maxRetries = 3
          $retryCount = 0
          while ($retryCount -lt $maxRetries) {
            try {
              flutter clean
              break
            } catch {
              $retryCount++
              if ($retryCount -eq $maxRetries) {
                Write-Host "Failed to run flutter clean after $maxRetries attempts"
                exit 1
              }
              Write-Host "Retry $retryCount of $maxRetries"
              Start-Sleep -Seconds 2
            }
          }
          
          Start-Sleep -Seconds 5
          
          # Run flutter pub get with retry mechanism
          $maxRetries = 3
          $retryCount = 0
          while ($retryCount -lt $maxRetries) {
            try {
              flutter pub get
              break
            } catch {
              $retryCount++
              if ($retryCount -eq $maxRetries) {
                Write-Host "Failed to run flutter pub get after $maxRetries attempts"
                exit 1
              }
              Write-Host "Retry $retryCount of $maxRetries"
              Start-Sleep -Seconds 2
            }
          }
          
          Start-Sleep -Seconds 5
          
      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          flutter clean
          flutter pub get
        
      - name: Run build_runner (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Start-Sleep -Seconds 5
          dart run build_runner clean
          Start-Sleep -Seconds 5
          dart run build_runner build --delete-conflicting-outputs
        
      - name: Run build_runner (macOS)
        if: matrix.os == 'macos-latest'
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Setup Xcode
        if: matrix.os == 'macos-latest'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
        
      - name: Build macOS app
        if: matrix.os == 'macos-latest'
        run: |
          flutter config --enable-macos-desktop
          flutter clean
          flutter pub get
          cd macos
          pod install
          cd ..
          flutter build macos --release --no-codesign
        
      - name: Build Windows app
        if: matrix.os == 'windows-latest'
        run: flutter build windows --release
        
      - name: Upload Windows artifact
        if: matrix.os == 'windows-latest'
        id: upload-windows-artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: build/windows/x64/runner/Release/
          
      - name: Upload macOS artifact
        if: matrix.os == 'macos-latest'
        id: upload-macos-artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-release
          path: build/macos/Build/Products/Release/

      - name: Notify Slack on Success
        if: always()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "${{ job.status == 'success' && '✅' || '❌' }} Flutter Desktop ${{ matrix.build }} 빌드\n배포환경: ${{ needs.set-environment.outputs.environment }}\n성공 유무: ${{ job.status }}\nOS: ${{ matrix.os }}\n저장소: ${{ github.repository }}\n브랜치: ${{ github.ref }}\n\n아티팩트 다운로드: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING-WEBHOOK